# Generated by Django 5.0.3 on 2024-04-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='catagory',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electornics', 'Electornics'), ('vehicle', 'Vehicle')], default='Fashion', max_length=50),
            preserve_default=False,
        ),
    ]
