# Generated by Django 5.0.3 on 2024-04-11 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='catagory',
            new_name='category',
        ),
    ]
