# Generated by Django 5.0.3 on 2024-04-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
