# Generated by Django 5.0.3 on 2024-04-12 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_is_live_alter_listing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 16, 19, 12, 174611)),
            preserve_default=False,
        ),
    ]
