# Generated by Django 5.0.3 on 2024-04-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('vehicle', 'Vehicle'), ('housing', 'Housing'), ('sports', 'Sports'), ('books', 'Books'), ('health', 'Health & Beauty'), ('toys', 'Toys & Games'), ('food', 'Food & Grocery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
