# Generated by Django 5.0.3 on 2024-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_category_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('electornics', 'Electornics'), ('vehicle', 'Vehicle')], max_length=50),
        ),
    ]
