# Generated by Django 5.0.6 on 2024-07-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='timestamp',
        ),
    ]
